# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: todo_app
#       MYSQL_USER: root
#       MYSQL_PASSWORD: todopassword
#     ports:
#       - '3306:3306'
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
